collections:
  pictures:
    order: 1
    output: true
  words:
    order: 2
    output: true
  things:
    order: 3
    output: true
  code:
    order: 4
    output: true
  me:
    order: 5
    output: true
